query: Generate exactly 5 highly detailed TikTok scripts for StyleBoost Accessory Set based on the creator's successful videos. Each script must include a compelling hook, complete shot-by-shot breakdown with timing, specific text overlay placement, detailed visual direction, music recommendations, and strategic hashtags. Make each script distinctly different to showcase the product in various scenarios.
lead_data: 
  id: "67d109795a08effb5160dcf0"
product_info:
  name: "StyleBoost Accessory Set"
  description: "A versatile set of fashion accessories that transform any outfit"
  goals: "Increase brand awareness and drive product interest"
  target_audience: "18-34 year old fashion-forward consumers"
  key_messages: "1. StyleBoost is unique and high-quality\n2. It enhances personal style\n3. It's versatile and easy to use"